version: "2"

services:
  app:
    image: ruby
    volumes:
      - .:/app
      - bundle_path:/usr/local/bundle
    environment:
      - PORT=5000
    working_dir: /app
    command: bundle exec rackup -o 0.0.0.0 -p 5000 -s puma
    ports:
      - "5000:5000"

volumes:
  bundle_path:
