version: "2"

services:
  web:
    build: .
    volumes:
      - .:/app
    command: forego start
    ports:
      - "5000:5000"

  heroku:
    build:
      context: .
      dockerfile: Dockerfile.heroku
    volumes:
      - .:/app
      - heroku:/root
    command: rake test

volumes:
  heroku:
